namespacePrefixes:
  adms: http://www.w3.org/ns/adms#
  dcat: http://www.w3.org/ns/dcat#
  foaf: http://xmlns.com/foaf/0.1/
  dct: http://purl.org/dc/terms/
  locn: http://www.w3.org/ns/locn#
  odrl: http://www.w3.org/ns/odrl/2/
  prov: http://www.w3.org/ns/prov#
  r5r: http://data.europa.eu/r5r/
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  sh: http://www.w3.org/ns/shacl#
  skos: http://www.w3.org/2004/02/skos/core#
  spdx: http://spdx.org/rdf/terms#
  time: http://www.w3.org/2006/time#
  vcard: http://www.w3.org/2006/vcard/ns#
  xsd: http://www.w3.org/2001/XMLSchema#

dataSources:
  nodeShapes:
    resolver: sparql
    location: sparql/nodeShapes.rq
    source: input/dcat-ap.ttl
    resultFrame:
      _key: targetClass
      targetClass: targetClass
      propertyShapes:
        _key: property
        propertyName: propertyName
        property: property
        description: description
        class:
          _value: class
          _prefix: true
        datatype:
          _value: datatype
          _prefix: true
        nodeKind:
          _value: nodeKind
          _prefix: true
        minCount: minCount
        maxCount: maxCount
  concepts:
    resolver: sparql
    location: sparql/concepts.rq
    source: input/input.ttl
    resultFrame:
      _key: prefLabel
      title: _title
      prefLabel: prefLabel
      altLabel:
        _value: altLabel
        _type: set
      broaderConcept:
        _value: broaderConcept
        _type: set
      notation: notation
      definition:
        _value: definition
        _type: set
  collections:
    resolver: sparql
    location: sparql/collection.rq
    source: input/input.ttl
    resultFrame:
      _key: label
      label: label
      members:
        _key: notation
        notation: notation
        definition: definition

templates:
  - templateLocation: skosTemplate.md
    outputLocation: output/
  - templateLocation: shaclTemplate.md
    outputLocation: output/
  - templateLocation: shaclTemplate2.md
    outputLocation: output/
