namespacePrefixes:
  dcat: http://www.w3.org/ns/dcat#
  dcterms: http://purl.org/dc/terms/
  skos: http://www.w3.org/2004/02/skos/core#
  xsd: http://www.w3.org/2001/XMLSchema#

dataSources:
  nodeShapes:
    resolver: sparql
    location: sparql/nodeShapes.rq
    source: input/dcat-ap.ttl
    resultFrame:
      _key: targetClass
      targetClass: targetClass
      propertyShapes:
        _key: property
        propertyName: propertyName
        property: property
        description: description
        class: class
#        class:
#          _prefix: true
        datatype: datatype
        nodeKind: nodeKind
        minCount: minCount
        maxCount: maxCount
  concepts:
    resolver: sparql
    location: sparql/concepts.rq
    source: input/input.ttl
    resultFrame:
      _key: prefLabel
      title: _title
      prefLabel: prefLabel
      altLabel:
        _value: altLabel
        _type: set
      broaderConcept:
        _value: broaderConcept
        _type: set
      notation: notation
      definition:
        _value: definition
        _type: set
  collections:
    resolver: sparql
    location: sparql/collection.rq
    source: input/input.ttl
    resultFrame:
      _key: label
      label: label
      members:
        _key: notation
        notation: notation
        definition: definition

templates:
  - templateLocation: skosTemplate.md
    outputLocation: output/
  - templateLocation: shaclTemplate.md
    outputLocation: output/
  - templateLocation: shaclTemplate2.md
    outputLocation: output/
