name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Build
        run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
